// Cadastro público (pré-ativação) — Nova Persea acquisition flow. Reached
// only via a per-lead secure link (?token=...), generated by Nay/Assistente
// from admin/lead-detail.js (see MockDB.generateRegistrationLink). This is
// NOT a client page: no shell, no nav, no dashboard — just the registration
// form, so a prospect can't see (or reach) anything else in the OS before
// she's actually activated. See MockDB.getLeadByToken/submitRegistration.
//
// Token security note (prototype limitation, flagged deliberately rather
// than silently assumed away): this app has no backend — every visitor's
// browser holds the full mock dataset in localStorage. getLeadByToken only
// ever *returns* one lead's safe subset for a given token, so the app-level
// contract (one link -> one lead's data, nothing else) holds. But a
// technical user could still open devtools and read every record in
// localStorage directly, same as they could on any client-side-only demo.
// Real cross-account isolation requires a real backend (Supabase RLS keyed
// on the token), which is out of scope here — see the delivery report.
import { MockDB, PROGRAM_LABEL_BY_SLUG } from '../shared/mock-db.js';
import { renderParticles, toast } from '../shared/ui.js';

const token = new URLSearchParams(location.search).get('token') || '';

document.body.innerHTML = `
  <div class="ambient"></div>
  <div class="grain"></div>
  <div id="particles-mount"></div>
  <div class="min-h-screen flex items-center justify-center px-4 py-12" style="position:relative; z-index:1;">
    <div class="w-full max-w-lg" id="reg-root"></div>
  </div>
`;
document.getElementById('particles-mount').innerHTML = renderParticles(14);
const root = document.getElementById('reg-root');

function maskCpf(v) {
  return v.replace(/\D/g, '').slice(0, 11)
    .replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2');
}
function maskCnpj(v) {
  return v.replace(/\D/g, '').slice(0, 14)
    .replace(/(\d{2})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1/$2').replace(/(\d{4})(\d{1,2})$/, '$1-$2');
}
function maskPhone(v) {
  return v.replace(/\D/g, '').slice(0, 11)
    .replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{4,5})(\d{4})$/, '$1-$2');
}
function maskCep(v) {
  return v.replace(/\D/g, '').slice(0, 8).replace(/(\d{5})(\d{1,3})$/, '$1-$2');
}

function invalidLinkView() {
  root.innerHTML = `
    <div class="card text-center">
      <p class="text-lg font-serif mb-2">Link inválido</p>
      <p class="text-sm" style="color:var(--muted);">Este link de cadastro não é válido ou já não está mais ativo. Fale com a equipe PERSEA para receber um novo link.</p>
    </div>
  `;
}

function confirmationView(fullName) {
  root.innerHTML = `
    <div class="card text-center">
      <p class="eyebrow mb-3">Cadastro recebido</p>
      <h1 class="font-serif text-2xl mb-4">Obrigada${fullName ? `, ${fullName.split(' ')[0]}` : ''}.</h1>
      <p class="text-sm" style="color:var(--muted); line-height:1.7;">Nossa equipe recebeu suas informações e seguirá com a preparação do seu contrato. Em breve você recebe os próximos passos.</p>
    </div>
  `;
}

function field(label, name, value, { type = 'text', required = true, placeholder = '', extra = '' } = {}) {
  return `
    <div>
      <label class="text-xs text-white/40 block mb-1">${label}</label>
      <input name="${name}" type="${type}" class="field" value="${value || ''}" placeholder="${placeholder}" ${required ? 'required' : ''} ${extra} />
    </div>
  `;
}

function formView(lead) {
  const info = lead.registrationInfo || {};
  const isPJ = info.partyType === 'PJ';
  const programLabel = lead.program ? (PROGRAM_LABEL_BY_SLUG[lead.program] || lead.program) : null;

  root.innerHTML = `
    <div class="card">
      <p class="eyebrow mb-2">${programLabel ? `Persea — ${programLabel}` : 'Persea'}</p>
      <h1 class="font-serif text-2xl mb-2">Vamos finalizar seu cadastro</h1>
      <p class="text-sm mb-8" style="color:var(--muted); line-height:1.7;">Precisamos de alguns dados para preparar seu contrato e organizar sua entrada no Persea. Leva apenas alguns minutos.</p>

      <form id="registration-form" class="space-y-8">
        <div>
          <p class="text-xs uppercase mb-4" style="color:var(--gold); letter-spacing:.12em;">Seus dados</p>
          <div class="space-y-4">
            ${field('Nome completo', 'fullName', info.fullName || lead.fullName)}
            ${field('Nome social', 'socialName', info.socialName, { required: false })}
            <div class="grid sm:grid-cols-2 gap-4">
              ${field('Data de nascimento', 'birthDate', info.birthDate, { type: 'date' })}
              <div>
                <label class="text-xs text-white/40 block mb-1">Tipo</label>
                <select name="partyType" id="party-type" class="field">
                  <option value="PF" ${!isPJ ? 'selected' : ''}>Pessoa Física</option>
                  <option value="PJ" ${isPJ ? 'selected' : ''}>Pessoa Jurídica</option>
                </select>
              </div>
            </div>
            <div class="grid sm:grid-cols-2 gap-4">
              ${field('CPF', 'cpf', info.cpf, { placeholder: '000.000.000-00' })}
              ${field('RG', 'rg', info.rg, { required: false })}
            </div>
            <div id="company-field" style="display:${isPJ ? 'block' : 'none'};">
              <p class="text-xs mb-3" style="color:var(--muted);">Pessoa Jurídica exige razão social e CNPJ para o contrato.</p>
              ${field('Nome da empresa', 'companyName', info.companyName, { required: isPJ })}
              ${field('CNPJ', 'cnpj', info.cnpj, { required: isPJ, placeholder: '00.000.000/0000-00' })}
            </div>
            <div class="grid sm:grid-cols-3 gap-4">
              ${field('Profissão', 'profession', info.profession)}
              ${field('Nacionalidade', 'nationality', info.nationality)}
              ${field('Estado civil', 'maritalStatus', info.maritalStatus, { required: false })}
            </div>
          </div>
        </div>

        <div>
          <p class="text-xs uppercase mb-4" style="color:var(--gold); letter-spacing:.12em;">Contato</p>
          <div class="grid sm:grid-cols-2 gap-4">
            ${field('Email', 'email', info.email || lead.email, { type: 'email' })}
            ${field('WhatsApp', 'whatsapp', info.whatsapp, { placeholder: '(00) 00000-0000' })}
          </div>
        </div>

        <div>
          <p class="text-xs uppercase mb-4" style="color:var(--gold); letter-spacing:.12em;">Endereço</p>
          <div class="grid sm:grid-cols-2 gap-4 mb-4">
            ${field('CEP', 'cep', info.cep, { placeholder: '00000-000' })}
            ${field('Cidade', 'city', info.city)}
          </div>
          <div class="grid sm:grid-cols-[1fr_auto] gap-4 mb-4">
            ${field('Rua', 'street', info.street)}
            ${field('Número', 'number', info.number)}
          </div>
          <div class="grid sm:grid-cols-2 gap-4 mb-4">
            ${field('Complemento', 'complement', info.complement, { required: false })}
            ${field('Bairro', 'neighborhood', info.neighborhood)}
          </div>
          ${field('Estado', 'state', info.state, { placeholder: 'UF' })}
        </div>

        <button type="submit" class="btn-primary block w-full text-center" style="padding-top:13px;padding-bottom:13px;">Enviar meus dados</button>
      </form>
    </div>
  `;

  // Production Audit Remediation Pass (High 6): companyName/cnpj toggle
  // `required` together with visibility, not just visibility alone — a
  // required-but-hidden (display:none) field breaks native HTML5 form
  // validation silently in most browsers (it can't focus an invisible
  // control to report the error), so relying on `required` while
  // display:none did nothing in practice. Submit-time validation below is
  // the real backstop either way.
  function syncCompanyFieldRequired(isPJNow) {
    document.getElementById('company-field').style.display = isPJNow ? 'block' : 'none';
    document.querySelector('input[name="companyName"]').required = isPJNow;
    document.querySelector('input[name="cnpj"]').required = isPJNow;
  }
  document.getElementById('party-type').addEventListener('change', (e) => { syncCompanyFieldRequired(e.target.value === 'PJ'); });
  syncCompanyFieldRequired(isPJ);
  root.querySelector('input[name="cpf"]').addEventListener('input', (e) => { e.target.value = maskCpf(e.target.value); });
  root.querySelector('input[name="cnpj"]').addEventListener('input', (e) => { e.target.value = maskCnpj(e.target.value); });
  root.querySelector('input[name="whatsapp"]').addEventListener('input', (e) => { e.target.value = maskPhone(e.target.value); });
  root.querySelector('input[name="cep"]').addEventListener('input', (e) => { e.target.value = maskCep(e.target.value); });

  document.getElementById('registration-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const fd = new FormData(e.target);
    const payload = Object.fromEntries(fd.entries());
    // Explicit, visible check — not just the `required` attribute above —
    // since this is the one place PJ data can still get lost (an old saved
    // draft, a browser that mishandles required-on-toggle, someone
    // resubmitting via devtools). Blocks submission rather than letting the
    // contract silently fall back to PF wording later (see
    // shared/contract-merge.js's assembleContratanteLine).
    if (payload.partyType === 'PJ' && (!payload.companyName?.trim() || !payload.cnpj?.trim())) {
      toast('Pessoa Jurídica exige nome da empresa e CNPJ preenchidos.', { tone: 'error' });
      return;
    }
    MockDB.submitRegistration(token, payload);
    confirmationView(payload.fullName);
  });
}

function render() {
  const lead = MockDB.getLeadByToken(token);
  if (!lead) { invalidLinkView(); return; }
  if (lead.alreadySubmitted) { confirmationView(lead.registrationInfo?.fullName || lead.fullName); return; }
  formView(lead);
}

render();
