
-- ============================================================
-- payments + payment_invoices
-- ============================================================
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p1-1', (select id from clients where legacy_id = 'client-1'), '2026-06-14', 266700, 'paid', '2026-06-13T10:00:00', 'https://pay.sumup.com/b2c/persea-marina-1', '2026-06-10T14:00:00', '2026-06-13T09:50:00');
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p1-1'), 'issued', '2026-06-13T11:00:00', '2026-06-14T09:00:00', 'nf-client-1-p1.pdf');
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p1-2', (select id from clients where legacy_id = 'client-1'), '2026-07-14', 266700, 'paid', '2026-07-14T09:30:00', 'https://pay.sumup.com/b2c/persea-marina-2', '2026-07-10T14:00:00', '2026-07-14T09:20:00');
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p1-2'), 'requested', '2026-08-01T10:00:00', NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p1-3', (select id from clients where legacy_id = 'client-1'), '2026-08-14', 266700, 'pending', NULL, 'https://pay.sumup.com/b2c/persea-marina-3', '2026-08-10T11:00:00', NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p1-3'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p1-4', (select id from clients where legacy_id = 'client-1'), '2026-09-14', 266700, 'pending', NULL, NULL, NULL, NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p1-4'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p2-1', (select id from clients where legacy_id = 'client-2'), '2026-07-15', 300000, 'paid', '2026-07-15T08:00:00', NULL, NULL, NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p2-1'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p2-2', (select id from clients where legacy_id = 'client-2'), '2026-08-01', 300000, 'overdue', NULL, 'https://pay.sumup.com/b2c/persea-julia-2', '2026-07-28T09:00:00', NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p2-2'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p2-3', (select id from clients where legacy_id = 'client-2'), '2026-09-01', 300000, 'pending', NULL, NULL, NULL, NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p2-3'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p3-1', (select id from clients where legacy_id = 'client-3'), '2026-06-01', 266700, 'paid', '2026-06-01T09:00:00', NULL, NULL, NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p3-1'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p3-2', (select id from clients where legacy_id = 'client-3'), '2026-07-01', 266700, 'paid', '2026-07-02T09:00:00', NULL, NULL, NULL);
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p3-2'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p3-3', (select id from clients where legacy_id = 'client-3'), '2026-08-01', 266700, 'pending', NULL, 'https://pay.sumup.com/b2c/persea-renata-3', '2026-07-25T09:00:00', '2026-08-05T16:40:00');
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p3-3'), 'not_requested', NULL, NULL, NULL);
insert into payments (legacy_id, client_id, due_date, amount_cents, status, paid_at, sumup_link_url, link_sent_at, reported_paid_at) values ('p6-1', (select id from clients where legacy_id = 'client-6'), '2026-08-05', 600000, 'paid', '2026-08-05T10:00:00', 'https://pay.sumup.com/b2c/persea-debora-1', '2026-08-02T10:00:00', '2026-08-05T09:45:00');
insert into payment_invoices (payment_id, status, requested_at, issued_at, file_name) values ((select id from payments where legacy_id = 'p6-1'), 'issued', '2026-08-05T10:30:00', '2026-08-06T09:00:00', 'nf-client-6-p1.pdf');

-- ============================================================
-- expenses
-- ============================================================
insert into expenses (legacy_id, expense_date, category, description, amount_cents) values ('e1', '2026-07-05', 'ferramentas', 'Assinaturas (Notion, Canva, Hubla)', 18000);
insert into expenses (legacy_id, expense_date, category, description, amount_cents) values ('e2', '2026-07-10', 'marketing', 'Anúncios Instagram', 45000);
insert into expenses (legacy_id, expense_date, category, description, amount_cents) values ('e3', '2026-08-01', 'equipe', 'Assistente administrativa (mensal)', 120000);
insert into expenses (legacy_id, expense_date, category, description, amount_cents) values ('e4', '2026-08-05', 'outros', 'Contabilidade', 30000);

-- ============================================================
-- agenda_items + meeting_recordings
-- ============================================================
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag1', 'admin_task', 'Preparar contrato da Bianca Souza', '2026-08-13T11:00:00', 'upcoming', (select id from clients where legacy_id = 'client-4'), NULL, 'Preparar contrato a partir das informações recebidas', '', '', '', '', NULL, NULL, NULL, '2026-08-10T09:00:00', '2026-08-10T09:00:00');
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag3', 'class', 'N Time Class — Tendências de Imagem 2026', '2026-08-13T20:00:00', 'upcoming', NULL, 'N Time Class', 'Aula mensal ao vivo sobre tendências de imagem', 'Revisar slides da aula anterior.', '', 'https://meet.google.com/exemplo-ntime', '', NULL, NULL, NULL, '2026-08-01T09:00:00', '2026-08-01T09:00:00');
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag4', 'group_meeting', 'Q&A Mensal — Turma Geral', '2026-08-14T19:00:00', 'upcoming', NULL, 'Q&A Mensal PERSEA', 'Perguntas e respostas ao vivo com todas as mentoradas', 'Revisar dúvidas enviadas durante a semana.', '', 'https://meet.google.com/exemplo-qna', '', NULL, NULL, NULL, '2026-08-01T09:00:00', '2026-08-01T09:00:00');
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag6', 'individual_meeting', 'E2 — Comunicação e Vendas', '2026-08-15T10:00:00', 'upcoming', (select id from clients where legacy_id = 'client-2'), NULL, 'Dificuldades de venda, comunicação, posicionamento e pitch', 'Revisar respostas do questionário antes da reunião.', '', 'https://meet.google.com/exemplo-julia', '', 60, 'nay', NULL, '2026-07-11T09:00:00', '2026-07-11T09:00:00');
insert into meeting_recordings (agenda_item_id, recording_status, transcript_status, recording_url, transcript_url, requires_attention, attention_note, sync_last_checked_at, sync_next_check_at, sync_google_account, sync_status, sync_attempts) values ((select id from agenda_items where legacy_id = 'ag6'), 'aguardando', 'nao_aplicavel', NULL, NULL, false, '', NULL, NULL, 'nay@persea.com.br', 'aguardando', 0);
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag15', 'individual_meeting', 'E1 — Extração e Essência', '2026-08-09T10:00:00', 'completed', (select id from clients where legacy_id = 'client-2'), NULL, 'Extração de marca e essência', '', '', 'https://meet.google.com/persea-julia-e1', '', 60, 'nay', NULL, '2026-08-02T09:00:00', '2026-08-09T18:00:00');
insert into meeting_recordings (agenda_item_id, recording_status, transcript_status, recording_url, transcript_url, requires_attention, attention_note, sync_last_checked_at, sync_next_check_at, sync_google_account, sync_status, sync_attempts) values ((select id from agenda_items where legacy_id = 'ag15'), 'erro', 'erro', NULL, NULL, true, 'O Google não retornou o link da gravação depois de várias tentativas — verifique manualmente no Drive e cole o link abaixo.', '2026-08-12T09:00:00', NULL, 'nay@persea.com.br', 'erro', 6);
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag18', 'checkpoint', 'Check-in — Dúvidas de Precificação', '2026-07-20T09:30:00', 'completed', (select id from clients where legacy_id = 'client-1'), NULL, 'Ajuste rápido na tabela de preços antes do lançamento', '', 'Alinhado — Marina vai testar o novo valor no próximo lote de clientes.', 'https://meet.google.com/persea-marina-checkin1', '', 30, 'nay', NULL, '2026-07-18T09:00:00', '2026-07-20T10:00:00');
insert into agenda_items (legacy_id, type, title, item_date, status, related_student_id, related_group_label, topic, prep_notes, general_notes, online_link, follow_up_notes, duration_minutes, assigned_to, assistant_persona, created_at, updated_at) values ('ag21', 'checkpoint', 'Check-in — Feedback de Proposta', '2026-08-25T14:00:00', 'upcoming', (select id from clients where legacy_id = 'client-1'), NULL, 'Ler uma proposta comercial antes de enviar', '', '', 'https://meet.google.com/persea-marina-checkin4', '', 30, 'nay', NULL, '2026-08-19T09:00:00', '2026-08-19T09:00:00');

-- ============================================================
-- meeting_requests
-- ============================================================
insert into meeting_requests (legacy_id, client_id, reason, status, assigned_to, created_at) values ('mr1', (select id from clients where legacy_id = 'client-1'), 'Tenho dúvida sobre como aplicar a Voz da Marca nas redes sociais.', 'assigned', 'nay', '2026-07-09T10:00:00');
insert into meeting_requests (legacy_id, client_id, reason, status, assigned_to, created_at) values ('mr2', (select id from clients where legacy_id = 'client-2'), 'Fiquei perdida em uma pergunta do questionário, queria confirmar se respondi certo.', 'pending', NULL, '2026-07-11T14:00:00');
