
-- ============================================================
-- questionnaires + questionnaire_questions
-- ============================================================
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-1'), 'Extração de Marca', 'submitted');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-1')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', 'Ser a estrategista de referência para marcas pessoais premium na América Latina.', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-1')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', 'Precisa, calorosa e alérgica a enrolação.', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-1')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', 'De especialista invisível a autoridade reconhecida.', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-1')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '5', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-2'), 'Extração de Marca', 'submitted');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-2')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', 'Ser vista como referência em finanças para mulheres autônomas.', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-2')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', 'Organizada, didática, mas ainda insegura para aparecer.', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-2')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', 'De confusão financeira para clareza e controle.', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-2')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '3', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-3'), 'Extração de Marca', 'submitted');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-3')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', 'Pela consultora que resolve o "caos operacional" de pequenos negócios.', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-3')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', 'Prática, direta, sem paciência para teoria sem aplicação.', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-3')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', 'De operação bagunçada para processo replicável.', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-3')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '6', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-4'), 'Extração de Marca', 'in_progress');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-4')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', '', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-4')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', '', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-4')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', '', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-4')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-5'), 'Extração de Marca', 'in_progress');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-5')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', '', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-5')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', '', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-5')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', '', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-5')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-6'), 'Extração de Marca', 'in_progress');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-6')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', '', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-6')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', '', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-6')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', '', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-6')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '', 3);
insert into questionnaires (client_id, title, status) values ((select id from clients where legacy_id = 'client-7'), 'Extração de Marca', 'not_started');
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q1', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-7')), 'Pelo que você quer ser conhecida daqui a 3 anos?', 'long_text', '', 0);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q2', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-7')), 'O que parece mais verdadeiro sobre quem você é agora?', 'long_text', '', 1);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q3', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-7')), 'Qual é a transformação que você ajuda as pessoas a fazerem?', 'long_text', '', 2);
insert into questionnaire_questions (legacy_id, questionnaire_id, question_text, question_type, answer, sort_order) values ('q4', (select id from questionnaires where client_id = (select id from clients where legacy_id = 'client-7')), 'Avalie sua confiança atual na sua marca pessoal (1-10)', 'scale', '', 3);

-- ============================================================
-- questionnaire_analyses + questionnaire_analysis_items
-- ============================================================
insert into questionnaire_analyses (client_id, version, generated_at, executive_summary, business_maturity, is_current) values ((select id from clients where legacy_id = 'client-1'), 1, '2026-07-01T10:00:00', 'Marina é uma profissional de alta competência cujo posicionamento externo ainda não acompanhou sua real expertise. Ela subestima sua autoridade por escrito, mas entrega além na prática.', 'Profissional estabelecida, pré-marca — entrega forte, narrativa fraca.', true);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'strength', 'Credibilidade técnica profunda', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'strength', 'Ponto de vista claro quando provocada', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'strength', 'Forte empatia com clientes', 2);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'goal', 'Ser reconhecida como autoridade de categoria, não generalista', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'goal', 'Elevar o valor cobrado por meio de posicionamento percebido', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'pain_point', 'Descreve-se com linguagem vaga e segura', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'pain_point', 'Sem narrativa consistente entre plataformas', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'opportunity', 'Um pilar de conteúdo com ponto de vista afiado', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'opportunity', 'Uma metodologia própria que já usa informalmente', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'suggested_question', 'O que você parou de explicar porque acha que as pessoas "já deveriam entender"?', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-1') and version = 1), 'suggested_question', 'Quem você secretamente acha que faz isso pior do que você?', 1);
insert into questionnaire_analyses (client_id, version, generated_at, executive_summary, business_maturity, is_current) values ((select id from clients where legacy_id = 'client-2'), 1, '2026-07-10T09:15:00', 'Júlia tem clareza técnica mas evita visibilidade — o principal obstáculo é exposição, não competência.', 'Início de carreira como autoridade — competência real, visibilidade ainda não construída.', true);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'strength', 'Didática natural', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'strength', 'Organização impecável de conteúdo', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'strength', 'Empatia com o público iniciante', 2);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'goal', 'Perder o medo de aparecer', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'goal', 'Construir autoridade em finanças pessoais', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'pain_point', 'Evita gravar vídeos e fazer lives', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'pain_point', 'Se compara constantemente a outras referências do nicho', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'opportunity', 'Formato de conteúdo escrito como porta de entrada antes do vídeo', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'opportunity', 'Comunidade de clientes como prova social', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'suggested_question', 'O que aconteceria se você postasse mesmo com medo?', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-2') and version = 1), 'suggested_question', 'Quem você imagina te vendo pela primeira vez?', 1);
insert into questionnaire_analyses (client_id, version, generated_at, executive_summary, business_maturity, is_current) values ((select id from clients where legacy_id = 'client-3'), 1, '2026-06-28T11:00:00', 'Renata já entrega resultado operacional forte, mas se posiciona como "faz-tudo" — o que dilui o valor percebido do seu trabalho mais estratégico.', 'Operadora experiente, migrando para posicionamento estratégico.', true);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'strength', 'Execução comprovada', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'strength', 'Linguagem direta e confiável', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'strength', 'Cases fortes de antes/depois', 2);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'goal', 'Ser vista como estrategista, não só executora', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'goal', 'Cobrar por diagnóstico, não só por implementação', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'pain_point', 'Aceita qualquer tipo de projeto', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'pain_point', 'Portfólio comunica serviço, não transformação', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'opportunity', 'Metodologia própria de diagnóstico operacional', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'opportunity', 'Reposicionar cases como estudos de transformação', 1);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'suggested_question', 'Que tipo de projeto você teria que recusar para subir de nível?', 0);
insert into questionnaire_analysis_items (analysis_id, item_kind, text, sort_order) values ((select id from questionnaire_analyses where client_id = (select id from clients where legacy_id = 'client-3') and version = 1), 'suggested_question', 'O que você faz que parece básico pra você mas é ouro pro cliente?', 1);

-- ============================================================
-- meeting_transcript_analyses + meeting_transcript_analysis_items (merged c.meeting/c.transcriptAnalysis -> agenda_items)
-- ============================================================

-- ============================================================
-- business_surveys / business_survey_responses
-- ============================================================

-- ============================================================
-- homework_tasks + homework_submissions
-- ============================================================
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-1'), 'Ler o Playbook', 'boolean', 'completed', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-1'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'completed', '', 1);
insert into homework_submissions (legacy_id, homework_task_id, kind, file_name, file_url, uploaded_at) values ('m1', (select id from homework_tasks where legacy_id = 'h2'), 'audio', 'pitch-treino-1.mp3', NULL, '2026-07-07T10:00:00');
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-1'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-2'), 'Ler o Playbook', 'boolean', 'pending', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-2'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-2'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-3'), 'Ler o Playbook', 'boolean', 'completed', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-3'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-3'), 'Perguntas de Reflexão', 'text_submission', 'completed', 'Os projetos que eu preciso recusar são os de organização de estoque pontual — não é o meu diagnóstico de fundo.', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-4'), 'Ler o Playbook', 'boolean', 'pending', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-4'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-4'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-5'), 'Ler o Playbook', 'boolean', 'pending', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-5'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-5'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-6'), 'Ler o Playbook', 'boolean', 'pending', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-6'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-6'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h1', (select id from clients where legacy_id = 'client-7'), 'Ler o Playbook', 'boolean', 'pending', '', 0);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h2', (select id from clients where legacy_id = 'client-7'), 'Gravação do Pitch (áudio ou vídeo)', 'media_upload', 'pending', '', 1);
insert into homework_tasks (legacy_id, client_id, title, task_type, status, submission_text, sort_order) values ('h3', (select id from clients where legacy_id = 'client-7'), 'Perguntas de Reflexão', 'text_submission', 'pending', '', 2);

-- ============================================================
-- client_activity_log
-- ============================================================
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'pitches_generated', 'Variações de pitch geradas', '2026-07-08T14:20:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'playbook_published', 'Playbook v1 publicado', '2026-07-06T11:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'playbook_draft_created', 'Rascunho do Playbook v1 gerado', '2026-07-05T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'meeting_analyzed', 'Transcrição da E1 analisada', '2026-07-04T16:10:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'questionnaire_submitted', 'Extração de Marca concluída', '2026-07-01T09:40:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-2'), 'questionnaire_submitted', 'Extração de Marca concluída', '2026-07-10T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'playbook_draft_created', 'Rascunho do Playbook v1 gerado', '2026-07-02T10:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'assessment_completed', 'Teste de Arquétipos concluído', '2026-06-30T15:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'meeting_analyzed', 'Transcrição da E3 analisada', '2026-06-29T16:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'questionnaire_submitted', 'Extração de Marca concluída', '2026-06-28T10:40:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-4'), 'onboarding_info_submitted', 'Informações de cadastro enviadas para o contrato', '2026-08-10T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-5'), 'onboarding_info_submitted', 'Informações de cadastro enviadas para o contrato', '2026-08-05T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-6'), 'whatsapp_status_changed', 'Adicionada ao grupo de WhatsApp', '2026-08-11T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-6'), 'signed_contract_uploaded', 'Contrato assinado enviado para o perfil da cliente', '2026-08-10T09:00:00');
insert into client_activity_log (client_id, event_type, text, occurred_at) values ((select id from clients where legacy_id = 'client-7'), 'lead_converted', 'Convertida de lead para cliente', '2026-08-17T09:00:00');

-- ============================================================
-- mood_log
-- ============================================================
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'questionnaire_submitted', 4, '2026-07-01T09:41:00');
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'playbook_experience', 5, '2026-07-06T19:31:00');
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-1'), 'quiz_completed', 5, '2026-07-06T19:46:00');
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-2'), 'questionnaire_submitted', 3, '2026-07-10T09:01:00');
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'questionnaire_submitted', 4, '2026-06-28T10:41:00');
insert into mood_log (client_id, context, mood, occurred_at) values ((select id from clients where legacy_id = 'client-3'), 'homework_task', 3, '2026-07-03T09:00:00');

-- ============================================================
-- content_activities (1:1)
-- ============================================================
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-1'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-2'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-3'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-4'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-5'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-6'), 'not_started', '', '', NULL);
insert into content_activities (client_id, status, submission, feedback, updated_at) values ((select id from clients where legacy_id = 'client-7'), 'not_started', '', '', NULL);
