
-- ============================================================
-- image_guides (4 per client, some fields blank pre-delivery)
-- ============================================================
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-1'), 'paleta_cores', 'https://example.com/guides/paleta_cores.pdf', '', 'Outono profundo — terrosos, vinho e dourado envelhecido; evita pastéis e preto puro perto do rosto.', 'https://www.canva.com/design/PLACEHOLDER-paleta-marina/edit', '2026-07-05T10:00:00');
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-1'), 'estilo', 'https://example.com/guides/estilo.pdf', '', 'Elegante-contemporâneo com toque autoral — alfaiataria solta, tecidos com textura, acessórios statement únicos.', 'https://www.canva.com/design/PLACEHOLDER-estilo-marina/edit', '2026-07-12T10:00:00');
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-1'), 'moodboard_ensaio', 'https://example.com/guides/moodboard_ensaio.pdf', '', 'Referências para o ensaio: luz dourada de fim de tarde, fundo neutro texturizado, poses de mãos em movimento (marca registrada dela em vídeo).', 'https://www.canva.com/design/PLACEHOLDER-mood-marina/edit', '2026-06-28T10:00:00');
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-1'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-2'), 'paleta_cores', 'https://example.com/guides/paleta_cores.pdf', '', 'Primavera clara — cores leves e luminosas (coral, verde-água, amarelo manteiga); metáis dourados favorecem mais que prateados.', 'https://www.canva.com/design/PLACEHOLDER-paleta-julia/edit', '2026-07-18T10:00:00');
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-2'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-2'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-2'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-3'), 'paleta_cores', 'https://example.com/guides/paleta_cores.pdf', '', 'Inverno clássico — contraste alto, cores puras e frias (azul-marinho, cereja, branco); evita tons terrosos/quebrados.', 'https://www.canva.com/design/PLACEHOLDER-paleta-renata/edit', '2026-06-20T10:00:00');
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-3'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-3'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-3'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-4'), 'paleta_cores', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-4'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-4'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-4'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-5'), 'paleta_cores', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-5'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-5'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-5'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-6'), 'paleta_cores', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-6'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-6'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-6'), 'guia_looks_mensal', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-7'), 'paleta_cores', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-7'), 'estilo', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-7'), 'moodboard_ensaio', NULL, '', '', '', NULL);
insert into image_guides (client_id, slug, file_url, note, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-7'), 'guia_looks_mensal', NULL, '', '', '', NULL);

-- ============================================================
-- digital_kits (1:1)
-- ============================================================
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-1'), 'https://example.com/kits/digital-kit.pdf', 'Template de feed + stories no tom terracota/dourado da marca, com variações para lançamento e bastidores.', 'https://www.canva.com/design/PLACEHOLDER-kit-marina/edit', '2026-07-20T10:00:00');
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-2'), NULL, '', '', NULL);
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-3'), NULL, '', '', NULL);
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-4'), NULL, '', '', NULL);
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-5'), NULL, '', '', NULL);
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-6'), NULL, '', '', NULL);
insert into digital_kits (client_id, file_url, summary, canva_url, delivered_at) values ((select id from clients where legacy_id = 'client-7'), NULL, '', '', NULL);

-- ============================================================
-- content_reviews
-- ============================================================
insert into content_reviews (legacy_id, client_id, review_type, ref_slug, title, note, file_url, summary, canva_url, status, created_at, resolved_at, nay_note) values ('rev1', (select id from clients where legacy_id = 'client-1'), 'image_guide', 'guia_looks_mensal', 'Guia de Looks do Mês — Agosto', 'Baseado nas fotos de guarda-roupa enviadas em julho.', 'https://example.com/guides/guia-looks-marina-ago.pdf', '', '', 'pending', '2026-08-16T14:00:00', NULL, '');
insert into content_reviews (legacy_id, client_id, review_type, ref_slug, title, note, file_url, summary, canva_url, status, created_at, resolved_at, nay_note) values ('rev2', (select id from clients where legacy_id = 'client-2'), 'image_guide', 'estilo', 'Guia de Estilo — Júlia', 'Primeira versão a partir da Direção da Marca.', 'https://example.com/guides/guia-estilo-julia.pdf', '', '', 'pending', '2026-08-15T11:00:00', NULL, '');
insert into content_reviews (legacy_id, client_id, review_type, ref_slug, title, note, file_url, summary, canva_url, status, created_at, resolved_at, nay_note) values ('rev3', (select id from clients where legacy_id = 'client-6'), 'image_guide', 'paleta_cores', 'Paleta de Cores — Débora', '', 'https://example.com/guides/paleta-debora.pdf', '', '', 'pending', '2026-08-17T10:00:00', NULL, '');

-- ============================================================
-- resources
-- ============================================================
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r1', 'Boas-vindas à Mentoria PERSEA', 'Vídeo de abertura explicando como funciona a jornada PERSEA.', 'posicionamento', NULL, '8 min', 'https://app.hub.la/m/8GhxpUirbFpF6c1tRrrC/s/5hh0gSean9Hf', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r2', 'Guia de Primeiros Passos', 'Documento de apoio para organizar as primeiras semanas de mentoria.', 'posicionamento', 'Essência, Comunicação e Vendas', NULL, 'https://pay.hubla.com.br/PLACEHOLDER-primeiros-passos', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r3', 'N Time Class — Tendências de Imagem', 'Aula mensal ao vivo sobre o universo de imagem e marca pessoal.', 'posicionamento', 'Imagem e Estratégia', '45 min', 'https://pay.hubla.com.br/PLACEHOLDER-n-time-class', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r4', 'Como Criar Conteúdo Sem Perder Autenticidade', 'Aula sobre alinhar a produção de conteúdo à sua Voz da Marca.', 'conteudo_autenticidade', 'Imagem e Estratégia', '32 min', 'https://pay.hubla.com.br/PLACEHOLDER-conteudo-autentico', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r5', 'Bastidores: Do Rascunho ao Post', 'Estudo de caso real de produção de conteúdo, do zero até publicar.', 'conteudo_autenticidade', NULL, '20 min', 'https://pay.hubla.com.br/PLACEHOLDER-bastidores', NULL, false);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r6', 'Comunicação Não-Violenta Aplicada a Vendas', 'Aula sobre comunicação clara e segura em conversas comerciais.', 'comunicacao', 'Essência, Comunicação e Vendas', '38 min', 'https://pay.hubla.com.br/PLACEHOLDER-comunicacao-nvc', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r7', 'Sua Voz em Público: Podcasts e Lives', 'Preparação prática para aparições ao vivo com confiança.', 'comunicacao', 'Posicionamento e Metas', '27 min', 'https://pay.hubla.com.br/PLACEHOLDER-voz-publico', NULL, false);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r8', 'Precificação com Confiança', 'Como comunicar valor e sustentar preços com segurança.', 'vendas', 'Negócio e Aquisição', '41 min', 'https://pay.hubla.com.br/PLACEHOLDER-precificacao', NULL, true);
insert into resources (legacy_id, title, description, track, phase_key, duration, hubla_url, recommendation, general_audience) values ('r9', 'Do Diagnóstico à Proposta', 'Estrutura de proposta comercial baseada em diagnóstico, não em improviso.', 'vendas', NULL, '35 min', 'https://pay.hubla.com.br/PLACEHOLDER-proposta', NULL, false);

-- ============================================================
-- resource_assignments
-- ============================================================
insert into resource_assignments (legacy_id, resource_id, client_id, reason, deadline, related_phase_or_meeting, assigned_at, completed) values ('ra1', (select id from resources where legacy_id = 'r5'), (select id from clients where legacy_id = 'client-1'), 'Você já publica bastante — este case ajuda a manter a autenticidade enquanto acelera o ritmo.', '2026-08-24', 'E3 — Imagem e Estratégia', '2026-08-10T09:00:00', false);
insert into resource_assignments (legacy_id, resource_id, client_id, reason, deadline, related_phase_or_meeting, assigned_at, completed) values ('ra2', (select id from resources where legacy_id = 'r7'), (select id from clients where legacy_id = 'client-3'), 'Sua próxima etapa envolve aparecer mais — essa aula prepara você para isso com segurança.', '2026-08-27', NULL, '2026-08-09T09:00:00', false);
insert into resource_assignments (legacy_id, resource_id, client_id, reason, deadline, related_phase_or_meeting, assigned_at, completed) values ('ra3', (select id from resources where legacy_id = 'r6'), (select id from clients where legacy_id = 'client-2'), 'Reforça a comunicação segura antes da próxima conversa comercial.', '2026-07-25', NULL, '2026-07-10T09:00:00', true);
insert into resource_assignments (legacy_id, resource_id, client_id, reason, deadline, related_phase_or_meeting, assigned_at, completed) values ('ra4', (select id from resources where legacy_id = 'r8'), (select id from clients where legacy_id = 'client-1'), 'Prática de precificação antes de revisar valores com clientes atuais.', '2026-07-20', NULL, '2026-07-05T09:00:00', false);
insert into resource_assignments (legacy_id, resource_id, client_id, reason, deadline, related_phase_or_meeting, assigned_at, completed) values ('ra5', (select id from resources where legacy_id = 'r9'), (select id from clients where legacy_id = 'client-3'), 'Estrutura de proposta para o próximo diagnóstico comercial.', '2026-08-05', NULL, '2026-07-20T09:00:00', true);
