
-- ============================================================
-- value_assessments
-- ============================================================
insert into value_assessments (legacy_id, client_id, status, questionnaire_version, started_at, submitted_at, analysis_started_at, published_at, updated_at) values ('bva1', (select id from clients where legacy_id = 'client-1'), 'in_progress', 1, '2026-08-10T09:00:00', NULL, NULL, NULL, '2026-08-12T11:00:00');
insert into value_assessments (legacy_id, client_id, status, questionnaire_version, started_at, submitted_at, analysis_started_at, published_at, updated_at) values ('bva3', (select id from clients where legacy_id = 'client-3'), 'published', 1, '2026-08-01T10:00:00', '2026-08-15T16:40:00', '2026-08-16T09:00:00', '2026-08-20T10:00:00', '2026-08-20T10:00:00');

-- ============================================================
-- value_assessment_answers_s1 + value_assessment_sales_channels
-- ============================================================
insert into value_assessment_answers_s1 (assessment_id, profession, specialty, region, service_mode, business_model, business_model_other, primary_offer_name, primary_offer_description, target_audience, sales_channels_other, main_problem, desired_outcome) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), 'Consultora de Comunicação e Marca Pessoal', 'Posicionamento para especialistas visíveis', 'Belo Horizonte, MG (atende todo o Brasil online)', 'Híbrido', 'Serviços individuais', '', 'Mentoria de Posicionamento Individual', 'Mentoria 1:1 de 3 meses para especialistas que querem se tornar referência.', 'Consultoras e terapeutas entre 30-45 anos, já com clientes, mas sem posicionamento claro.', '', 'Sinto que cobro pouco pelo tempo que dedico e não sei se meu preço está alinhado ao mercado.', 'Ter clareza se posso aumentar o preço e como estruturar isso sem perder clientes.');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), 'Indicações');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), 'Instagram');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), 'WhatsApp');
insert into value_assessment_answers_s1 (assessment_id, profession, specialty, region, service_mode, business_model, business_model_other, primary_offer_name, primary_offer_description, target_audience, sales_channels_other, main_problem, desired_outcome) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Estrategista de Marca e Consultora de Negócios', 'Estratégia comercial para pequenos negócios de serviço', 'São Paulo, SP (atende online)', 'Online', 'Combinação de modelos', '', 'Consultoria de Estratégia Comercial', 'Projeto de 6 semanas para reestruturar oferta e precificação.', 'Donas de pequenos negócios de serviço faturando entre R$10 mil e R$30 mil/mês.', '', 'Não sei se meu preço cobre meus custos reais — nunca calculei isso com precisão.', 'Sair com um preço que eu confie para negociar sem insegurança.');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Indicações');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Instagram');
insert into value_assessment_sales_channels (assessment_id, channel) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Anúncios');

-- ============================================================
-- value_assessment_answers_s2 + value_offers
-- ============================================================
insert into value_assessment_answers_s2 (assessment_id, monthly_revenue_cents, monthly_revenue_precision, monthly_clients, capacity_utilization) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), NULL, '', NULL, '');
insert into value_offers (legacy_id, assessment_id, name, current_price_cents, delivery_type, delivery_type_other, delivery_minutes, delivery_unit, requires_post_work, post_work_hours, avg_monthly_sales, has_capacity_limit, capacity_limit, payment_method, payment_method_other, installments, offers_discount, discount_notes, pays_commission, commission_notes, direct_cost_per_sale_cents, price_assessment, price_last_changed_at, price_change_reason) values ('off-marina-1', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), 'Mentoria de Posicionamento Individual (3 meses)', 480000, 'Online', '', 90, 'sessao', 'Sim', 1, 4, 'Sim', 6, 'Parcelado', '', 3, 'Só à vista, 5%.', '', '', '', 12000, 'Um pouco baixo', 'Há cerca de 8 meses', 'Reajuste simples de inflação.');
insert into value_assessment_answers_s2 (assessment_id, monthly_revenue_cents, monthly_revenue_precision, monthly_clients, capacity_utilization) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 2200000, 'Aproximado', 8, 'Entre 76% e 90%');
insert into value_offers (legacy_id, assessment_id, name, current_price_cents, delivery_type, delivery_type_other, delivery_minutes, delivery_unit, requires_post_work, post_work_hours, avg_monthly_sales, has_capacity_limit, capacity_limit, payment_method, payment_method_other, installments, offers_discount, discount_notes, pays_commission, commission_notes, direct_cost_per_sale_cents, price_assessment, price_last_changed_at, price_change_reason) values ('off-renata-1', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Consultoria de Estratégia Comercial (projeto 6 semanas)', 650000, 'Online', '', 120, 'sessao', 'Sim', 3, 3, 'Sim', 4, 'Entrada + saldo', '', 2, 'Não', '', 'Não', '', 20000, 'Não sei avaliar', 'Nunca alterado', '');
insert into value_offers (legacy_id, assessment_id, name, current_price_cents, delivery_type, delivery_type_other, delivery_minutes, delivery_unit, requires_post_work, post_work_hours, avg_monthly_sales, has_capacity_limit, capacity_limit, payment_method, payment_method_other, installments, offers_discount, discount_notes, pays_commission, commission_notes, direct_cost_per_sale_cents, price_assessment, price_last_changed_at, price_change_reason) values ('off-renata-2', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Diagnóstico Express (sessão única)', 90000, 'Online', '', 60, 'sessao', 'Não', NULL, 5, 'Não', NULL, 'À vista', '', NULL, 'Não', '', 'Não', '', 3000, 'Um pouco baixo', 'Há 1 ano', 'Nunca revisado.');

-- ============================================================
-- value_assessment_answers_s3 + value_fixed_costs + value_variable_costs
-- ============================================================
insert into value_assessment_answers_s3 (assessment_id, separates_finances, tracks_monthly, variable_cost_notes, seasonal_notes) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), '', '', '', '');
insert into value_assessment_answers_s3 (assessment_id, separates_finances, tracks_monthly, variable_cost_notes, seasonal_notes) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Sim', 'Às vezes', 'Anúncios variam bastante mês a mês.', 'Dezembro e janeiro sempre mais fracos.');
insert into value_fixed_costs (legacy_id, assessment_id, category, description, monthly_amount_cents, is_estimate) values ('fc-r1', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Softwares e plataformas', 'CRM, agenda online e e-mail marketing', 28000, false);
insert into value_fixed_costs (legacy_id, assessment_id, category, description, monthly_amount_cents, is_estimate) values ('fc-r2', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Contabilidade', 'Contador mensal', 35000, false);
insert into value_fixed_costs (legacy_id, assessment_id, category, description, monthly_amount_cents, is_estimate) values ('fc-r3', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Marketing e anúncios', 'Anúncios Instagram/Google', 90000, true);
insert into value_fixed_costs (legacy_id, assessment_id, category, description, monthly_amount_cents, is_estimate) values ('fc-r4', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Equipe, assistentes e prestadores recorrentes', 'Assistente virtual (10h/semana)', 120000, false);
insert into value_variable_costs (legacy_id, assessment_id, category, calculation_type, description, amount_cents, percentage, is_estimate) values ('vc-r1', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Impostos', 'percentage', 'Simples Nacional', NULL, 6, false);
insert into value_variable_costs (legacy_id, assessment_id, category, calculation_type, description, amount_cents, percentage, is_estimate) values ('vc-r2', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Taxas de cartão', 'percentage', 'Taxa de parcelamento', NULL, 3.5, true);

-- ============================================================
-- value_assessment_answers_s4 + value_capacity_limiters
-- ============================================================
insert into value_assessment_answers_s4 (assessment_id, desired_weekly_hours, admin_hours, sales_hours, marketing_hours, planning_hours, delivery_hours_available, work_days_per_week, workload_preference, deliverable_volume_capacity, max_volume_achieved, was_sustainable, capacity_limiters_other, demand_double_scenario, capacity_increase_ideas) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '', '', '', '');
insert into value_assessment_answers_s4 (assessment_id, desired_weekly_hours, admin_hours, sales_hours, marketing_hours, planning_hours, delivery_hours_available, work_days_per_week, workload_preference, deliverable_volume_capacity, max_volume_achieved, was_sustainable, capacity_limiters_other, demand_double_scenario, capacity_increase_ideas) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 30, 6, 5, 5, 3, NULL, 5, 'Sim', 6, 8, 'Não', '', 'Eu não conseguiria atender com a qualidade que tenho hoje.', 'Contratar uma segunda assistente para tirar tarefas administrativas de mim.');
insert into value_capacity_limiters (assessment_id, limiter) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Tempo');
insert into value_capacity_limiters (assessment_id, limiter) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Processo comercial');

-- ============================================================
-- value_assessment_answers_s5
-- ============================================================
insert into value_assessment_answers_s5 (assessment_id, desired_monthly_revenue_cents, desired_revenue_timeframe, desired_pro_labore_cents, min_personal_expenses_cents, reserve_emergency_cents, reserve_reinvestment_cents, reserve_growth_cents, reserve_vacation_cents, reserve_other_cents, business_debt, expansion_goal, safety_margin_pct, can_cover_costs_today, current_priority) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, '', '');
insert into value_assessment_answers_s5 (assessment_id, desired_monthly_revenue_cents, desired_revenue_timeframe, desired_pro_labore_cents, min_personal_expenses_cents, reserve_emergency_cents, reserve_reinvestment_cents, reserve_growth_cents, reserve_vacation_cents, reserve_other_cents, business_debt, expansion_goal, safety_margin_pct, can_cover_costs_today, current_priority) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 3000000, '6 meses', 1200000, 800000, 100000, 150000, 100000, 50000, NULL, 'Não', 'Quero contratar uma segunda assistente em até 6 meses.', 15, 'Parcialmente', 'Aumentar margem');

-- ============================================================
-- value_assessment_answers_s6 + value_references
-- ============================================================
insert into value_assessment_answers_s6 (assessment_id, experience_level, years_in_field, qualifications, differentiator, why_best_clients_choose, transformation_delivered, extras_included, common_objections, price_questioned, loss_reason, references_intro, knows_reference_prices, desired_perception, price_matches_positioning, price_matches_positioning_why, demand_level, waitlist_exists, lost_sales_due_to_capacity, believes_could_sustain_higher_price, price_increase_doubts) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-1')), '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
insert into value_assessment_answers_s6 (assessment_id, experience_level, years_in_field, qualifications, differentiator, why_best_clients_choose, transformation_delivered, extras_included, common_objections, price_questioned, loss_reason, references_intro, knows_reference_prices, desired_perception, price_matches_positioning, price_matches_positioning_why, demand_level, waitlist_exists, lost_sales_due_to_capacity, believes_could_sustain_higher_price, price_increase_doubts) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Experiente', '7 anos', 'MBA em Gestão, 7 anos de mercado, cases publicados.', 'Combino estratégia comercial com posicionamento de marca — a maioria só faz um dos dois.', 'Porque entrego um plano prático, não só teoria.', 'Sair de "não sei cobrar" para uma oferta estruturada com preço defensável.', 'Modelo de proposta comercial pronto e 30 dias de suporte por WhatsApp.', '"Está caro" e "preciso pensar".', 'Às vezes', 'Achar que consegue resolver sozinha.', 'Duas outras consultorias de estratégia comercial que atuam com o mesmo público.', 'Em parte', 'Estrategista sênior, não "mais uma consultora".', 'Não', 'Meu preço está abaixo do que minha experiência sustenta.', 'Acima da capacidade', 'Sim', 'Sim', 'Sim', 'Medo de perder as clientes mais antigas que pagam o preço atual.');
insert into value_references (legacy_id, assessment_id, name, product, known_price, source) values ('ref-r1', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Consultoria concorrente A', 'Projeto similar de 6 semanas', 'R$ 5.000 a R$ 7.000', 'Site público');
insert into value_references (legacy_id, assessment_id, name, product, known_price, source) values ('ref-r2', (select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Consultoria concorrente B', 'Mentoria em grupo', 'R$ 2.500', 'Indicação de cliente');

-- ============================================================
-- value_assessment_review_status
-- ============================================================

-- ============================================================
-- value_assessment_scenarios
-- ============================================================

-- ============================================================
-- value_recommendations + value_recommendation_factors
-- ============================================================
insert into value_recommendations (assessment_id, offer_id, status, strategic_price_cents, mathematical_minimum_cents, effective_date, review_date, strategic_justification, risks, created_by, created_at) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), (select id from value_offers where legacy_id = 'off-renata-1'), 'published', 950000, 720000, '2026-08-20', '2027-02-20', 'O preço atual (R$ 6.500) fica abaixo da necessidade operacional bruta considerando a capacidade realista, e das referências de mercado (R$5.000–7.000). Com 7 anos de experiência e demanda acima da capacidade, R$ 9.500 é sustentável sem perder o posicionamento.', 'Pode gerar objeção pontual de clientes recorrentes acostumadas ao preço antigo — comunicar com antecedência.', 'nay', '2026-08-20T10:00:00');
insert into value_recommendation_factors (assessment_id, factor) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Necessidade operacional');
insert into value_recommendation_factors (assessment_id, factor) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Referências de mercado');
insert into value_recommendation_factors (assessment_id, factor) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 'Nível de experiência');

-- ============================================================
-- value_published_deliverables
-- ============================================================
insert into value_published_deliverables (assessment_id, strategic_price_cents, explanation, recommendation_date, review_date, mathematical_minimum_cents, published_at) values ((select id from value_assessments where client_id = (select id from clients where legacy_id = 'client-3')), 950000, 'Seu preço atual está abaixo do que sua experiência e a demanda atual sustentam. Recomendamos R$ 9.500 para o projeto de Consultoria de Estratégia Comercial, com vigência a partir de 20/08/2026.', '2026-08-20', '2027-02-20', 720000, '2026-08-20T10:00:00');

-- ============================================================
-- price_history
-- ============================================================
insert into price_history (legacy_id, client_id, offer_id, offer_name, recommendation_id, previous_price_cents, new_price_cents, reason, effective_date, review_date, created_by, created_at) values ('ph1', (select id from clients where legacy_id = 'client-3'), (select id from value_offers where legacy_id = 'off-renata-1'), 'Consultoria de Estratégia Comercial (projeto 6 semanas)', (select id from value_assessments where legacy_id = 'bva3'), 650000, 950000, 'O preço atual fica abaixo da necessidade operacional bruta e das referências de mercado; experiência e demanda sustentam o novo preço.', '2026-08-20', '2027-02-20', 'nay', '2026-08-20T10:00:00');

-- ============================================================
-- premium_upgrade_interests
-- ============================================================
